config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "how_tos#index"

  get '/profile' => "users#profile"
  get '/admin_panel/users' => 'users#admin_edit_user'
  get '/admin_panel/howtos' => 'users#admin_edit_howto'

  get '/how_to/new' => "how_tos#new"
  put '/how_to/create' => "how_tos#create"
  delete '/how_to/delete/:how_to_id' => "how_tos#delete"
  get '/show/:how_to_id' => "how_tos#show"
  get '/random' => 'how_tos#random'
  

  put '/like/:how_to_id' => 'likes#like'
  delete '/unlike/:how_to_id' => 'likes#unlike'
  get '/like/:how_to_id/index' => 'likes#index'

  get '/steps/new' => "steps#new"
  put '/steps/create' => "steps#create"

  put '/comment/create' => 'comments#create'
  delete 'comment/delete/:id' => 'comment#delete'

  get '/attempt/new' => 'attempts#new'
  put '/attempt/create' => 'attempts#create'

  get '/user/edit' => 'users#edit'
  post '/user/update' => 'users#update'
  post '/user/:id/promote' => 'users#promote'
  post '/user/:id/demote' => 'users#demote'
  delete '/user/:id/delete' => "users#destroy"
  get '/user/:id/show' => 'users#show'

  put '/rating/:user_id/:how_to_id/' => 'how_tos#new_rating'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

    def configure_devise_permitted_parameters
      registration_params = [:first_name, :last_name, :email, :password, :password_confirmation]

      if params[:action] == 'update'
        devise_parameter_sanitizer.for(:account_update) { 
          |u| u.permit(registration_params << :current_password)
        }
      elsif params[:action] == 'create'
        devise_parameter_sanitizer.for(:sign_up) { 
          |u| u.permit(registration_params) 
        }
      end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_admin.html.erb
<ul>
<li><%= link_to "Users", '/admin_panel/users' %></li>
<li><%= link_to "How To's", '/admin_panel/howtos' %></li>
</ul>

app/views/application/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <h1 class="logo"><a class="brand" href="http://www.iexperience.co.za">iXperience</a></h1>
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            		<li> <%= link_to "How To iX", root_path, class: "btn btn-medium" %>
            <% if user_signed_in? %>
			 		      <li> <%= link_to "#{current_user.first_name} #{current_user.last_name}", '/profile', class: "btn btn-medium" %>
					      <li> <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' ,class: "btn btn-medium" %>
				    <% else %>
				  	    <li> <%= link_to "Sign in", user_session_path, class: "btn btn-medium" %>
                <li> <%= link_to "Sign up", new_registration_path(User.new()), class: "btn btn-medium" %>
				    <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div><!-- .navbar -->